#version: "3.9"

services:
  # db:
  #   image: postgres:15
  #   container_name: gown-db
  #   environment:
  #     POSTGRES_DB: ConvocationGownDb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #     - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gown-api
    ports:
      - "5050:5050"
    environment:
      # ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=ConvocationGownDb;Username=postgres;Password=postgres
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
    depends_on: []
    # depends_on:
    #   - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gown-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
# volumes:
#   pgdata: