services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gown-api
    ports:
      - "5050:5050"
    environment:
      # ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=ConvocationGownDb;Username=postgres;Password=postgres
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gown-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
